package quuid

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha512"
	"crypto/subtle"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"io"
)

// IDSize is the binary size of an ID in bytes.
const (
	IDSize   = 32
	idPrefix = "qid_"
)

// ID is a 256-bit cryptographically random identifier.
//
// A quantum computer running an idealized Grover search would still require
// roughly 2^128 work to guess a specific uniformly random ID. ID is not an
// authentication mechanism; use Token for secrets and access credentials.
type ID [IDSize]byte

// NewID returns a new ID generated by crypto/rand.
func NewID() (ID, error) {
	return NewIDFromReader(rand.Reader)
}

// NewIDFromReader returns a new ID using r as its entropy source.
// It is primarily useful for deterministic testing and specialized HSM/DRBG integrations.
func NewIDFromReader(r io.Reader) (ID, error) {
	var id ID
	if r == nil {
		return id, fmt.Errorf("quuid: nil entropy reader")
	}
	if _, err := io.ReadFull(r, id[:]); err != nil {
		return ID{}, fmt.Errorf("quuid: read entropy: %w", err)
	}
	if allZero(id[:]) {
		return ID{}, ErrZeroEntropy
	}
	return id, nil
}

// MustNewID is like NewID but panics if the operating system entropy source fails.
func MustNewID() ID {
	id, err := NewID()
	if err != nil {
		panic(err)
	}
	return id
}

// DeriveID deterministically derives an ID using SHA-512/256 and domain separation.
// The result is stable but not secret and may reveal equality of equal inputs.
func DeriveID(namespace string, data []byte) ID {
	h := sha512.New512_256()
	writeFrame(h, []byte("github.com/MeViksry/quuid/derive-id/v1"), []byte(namespace), data)
	var id ID
	copy(id[:], h.Sum(nil))
	return id
}

// DeriveIDKeyed deterministically derives an unguessable ID using HMAC-SHA-512/256.
// secret must contain at least 32 random bytes.
func DeriveIDKeyed(secret []byte, namespace string, data []byte) (ID, error) {
	if len(secret) < 32 {
		return ID{}, ErrWeakSecret
	}
	h := hmac.New(sha512.New512_256, secret)
	writeFrame(h, []byte("github.com/MeViksry/quuid/derive-id-keyed/v1"), []byte(namespace), data)
	var id ID
	copy(id[:], h.Sum(nil))
	return id, nil
}

// ParseID parses an ID from its supported text representations.
func ParseID(s string) (ID, error) {
	raw, err := decodeText(s, idPrefix, IDSize)
	if err != nil {
		return ID{}, err
	}
	var id ID
	copy(id[:], raw)
	return id, nil
}

// MustParseID is like ParseID but panics on malformed input.
func MustParseID(s string) ID {
	id, err := ParseID(s)
	if err != nil {
		panic(err)
	}
	return id
}

// String returns the canonical text representation.
func (id ID) String() string { return encodeText(idPrefix, id[:]) }

// Hex returns the lowercase hexadecimal representation without a type prefix.
func (id ID) Hex() string { return fmt.Sprintf("%x", id[:]) }

// Bytes returns a defensive copy of the binary representation.
func (id ID) Bytes() []byte { return append([]byte(nil), id[:]...) }

// IsZero reports whether every byte is zero.
func (id ID) IsZero() bool { return allZero(id[:]) }

// Equal reports whether two values contain identical bytes.
func (id ID) Equal(other ID) bool {
	return subtle.ConstantTimeCompare(id[:], other[:]) == 1
}

// Compare compares two values lexicographically and returns -1, 0, or 1.
func (id ID) Compare(other ID) int {
	for i := range id {
		if id[i] < other[i] {
			return -1
		}
		if id[i] > other[i] {
			return 1
		}
	}
	return 0
}

// MarshalText implements encoding.TextMarshaler.
func (id ID) MarshalText() ([]byte, error) { return id.AppendText(nil) }

// AppendText appends the canonical text representation to dst.
func (id ID) AppendText(dst []byte) ([]byte, error) {
	return appendEncodedText(dst, idPrefix, id[:]), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (id *ID) UnmarshalText(text []byte) error {
	if id == nil {
		return fmt.Errorf("quuid: UnmarshalText on nil *ID")
	}
	parsed, err := ParseID(string(text))
	if err != nil {
		return err
	}
	*id = parsed
	return nil
}

// MarshalJSON implements json.Marshaler.
func (id ID) MarshalJSON() ([]byte, error) { return json.Marshal(id.String()) }

// UnmarshalJSON implements json.Unmarshaler.
func (id *ID) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return ErrNilValue
	}
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return fmt.Errorf("quuid: decode ID JSON: %w", err)
	}
	return id.UnmarshalText([]byte(value))
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (id ID) MarshalBinary() ([]byte, error) { return id.AppendBinary(nil) }

// AppendBinary appends the binary representation to dst.
func (id ID) AppendBinary(dst []byte) ([]byte, error) {
	return append(dst, id[:]...), nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
func (id *ID) UnmarshalBinary(data []byte) error {
	if id == nil {
		return fmt.Errorf("quuid: UnmarshalBinary on nil *ID")
	}
	if len(data) != IDSize {
		return ErrInvalidLength
	}
	copy(id[:], data)
	return nil
}

// Scan implements database/sql.Scanner.
func (id *ID) Scan(src any) error {
	if id == nil {
		return fmt.Errorf("quuid: Scan on nil *ID")
	}
	parsed, err := scanIDSource(src)
	if err != nil {
		return err
	}
	*id = parsed
	return nil
}

// Value implements database/sql/driver.Valuer.
func (id ID) Value() (driver.Value, error) { return id.String(), nil }

func scanIDSource(src any) (ID, error) {
	switch value := src.(type) {
	case nil:
		return ID{}, ErrNilValue
	case string:
		return ParseID(value)
	case []byte:
		if len(value) == IDSize {
			var id ID
			copy(id[:], value)
			return id, nil
		}
		return ParseID(string(value))
	default:
		return ID{}, fmt.Errorf("%w: %T", ErrInvalidSource, src)
	}
}
